# Sử dụng nginx:latest làm base image
FROM nginx:latest

# Sao chép tệp index.html vào thư mục mặc định của Nginx
COPY index.html /usr/share/nginx/html/index.html

# Mở cổng 80
EXPOSE 80

# Nginx tự động chạy khi container bắt đầu
CMD ["nginx", "-g", "daemon off;"]
