# Sử dụng node:18-alpine làm base image
FROM node:18-alpine

# Thiết lập thư mục làm việc trong container
WORKDIR /app

# Sao chép package.json và package-lock.json vào container
COPY package.json package-lock.json /app/

# Cài đặt các dependencies của ứng dụng React
RUN npm install

# Sao chép tất cả mã nguồn vào trong container
COPY . /app/

# Build ứng dụng React
RUN npm run build

# Cung cấp thư mục build cho Nginx
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

# Mở cổng 80
EXPOSE 80

# Chạy Nginx để phục vụ ứng dụng React
CMD ["nginx", "-g", "daemon off;"]
